language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
env:
    - DJANGO="django>=1.8,<1.9"
    - DJANGO="django>=1.9,<1.10"
    - DJANGO="django>=1.10,<1.11"
matrix:
    exclude:
        - python: "3.3"
          env: DJANGO="django>=1.8,<1.9"
        - python: "3.3"
          env: DJANGO="django>=1.9,<1.10"
        - python: "3.3"
          env: DJANGO="django>=1.10,<1.11"
install:
    - pip install -U pip
    - pip install $DJANGO
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
script:
    - .githooks/pre-commit -f
    - nosetests --with-coverage --cover-package=ixprofile_client
sudo: false
after_success:
    coveralls
deploy:
    provider: pypi
    user: ixa
    password:
        secure: KotqwXcFnooWKlSp1jM98898loE9ugWpba7tXGcDFuHhXQGT/wXtNgzROa2EhPxs7IYfQtxq4HD3dadYSziuUzHRTTjg5YUiW9Gx4N0gFtfthraroKu4IB62B9k84YPmxIIZZNvkJOSd1Ip5x2/+TJntPcroi0UK4GFRhLmcOKM=
    server: https://pypi.python.org/pypi
    on:
        tags: true
        all_branches: true
        python: 3.4
        condition: "\"$TRAVIS_TAG\" = \"v$(python setup.py --version)\""
