language: python
python:
    - "2.7"
    - "3.4"
install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
script:
    - .githooks/pre-commit -f
    - nosetests --with-coverage --cover-package=ixprofile_client
sudo: false
after_success:
    coveralls
